export const TOGGLE_LEFT_HAND_NAV = 'TOGGLE_LEFT_HAND_NAV'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

export const SHOW_HEADER_MODULES = 'SHOW_HEADER_MODULES'
export const HIDE_HEADER_MODULES = 'HIDE_HEADER_MODULES'
